[package]
name = "board-games"
version = "0.1.0"
edition = "2024"
rust-version = "1.90"

[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
base64 = "0.22.1"
clap = { version = "4.5.58", features = ["derive"] }
rand = { version = "0.9.2", features = ["std_rng"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
sha2 = "0.10.9"
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio-rustls", "postgres", "uuid", "json", "migrate", "macros"] }
thiserror = "2.0.12"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread", "signal", "net"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "json"] }
uuid = { version = "1.18.0", features = ["v4", "serde"] }

[dev-dependencies]
tower = { version = "0.5.2", features = ["util"] }
