FROM rust:1.90-bookworm AS build
WORKDIR /source
COPY Cargo.toml Cargo.lock ./
COPY src ./src
COPY migrations ./migrations
RUN cargo build --release --locked

FROM gcr.io/distroless/cc-debian12:nonroot
COPY --from=build /source/target/release/board-games /board-games-api
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/board-games-api"]
