apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: board-games-local
  labels:
    app.kubernetes.io/part-of: board-games
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
